<?php

// autoload.php @generated by Composer

require_once("./PHPMailer_5.2.0/class.phpmailer.php");
$mail = new PHPMailer;
$mail->setFrom('daveswebtesting@gmail.com', 'Your Name');
$mail->addAddress('daveswebtesting@gmail.com', 'My Friend');
$mail->Subject  = 'First PHPMailer Message';
$mail->Body     = 'Hi! This is my third e-mail sent through PHPMailer, i finally got the darn thing 
working!';
if(!$mail->send()) {
  echo 'Message was not sent.';
  echo 'Mailer error: ' . $mail->ErrorInfo;
} else {
  echo 'Message has been sent.';
}
    
	 ?>